name: arcon_app
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  step_progress_indicator: ^1.0.2
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  provider: ^6.0.5
  printing: ^5.11.0
  cloud_firestore: ^4.9.1
  firebase_auth: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
