// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6jflP1hWvXMvH6ZeKslSCWC38QLjcO_w',
    appId: '1:812229010081:web:b0eb084af5e4aae05f06e0',
    messagingSenderId: '812229010081',
    projectId: 'arcon-2023',
    authDomain: 'arcon-2023.firebaseapp.com',
    storageBucket: 'arcon-2023.appspot.com',
    measurementId: 'G-G8T4N32Z06',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFgPu2A4zRSKjXxeMlGiYdT1a1EZkaOCY',
    appId: '1:812229010081:android:618c36db913203185f06e0',
    messagingSenderId: '812229010081',
    projectId: 'arcon-2023',
    storageBucket: 'arcon-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBy9jLZ8XmTYQePGw19owRlO6DqQxUziXE',
    appId: '1:812229010081:ios:69c1b5fadefbef185f06e0',
    messagingSenderId: '812229010081',
    projectId: 'arcon-2023',
    storageBucket: 'arcon-2023.appspot.com',
    iosClientId: '812229010081-ma1q76p8efvmnjcg9042el37ogaceooq.apps.googleusercontent.com',
    iosBundleId: 'com.example.arconApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBy9jLZ8XmTYQePGw19owRlO6DqQxUziXE',
    appId: '1:812229010081:ios:e2158ceca329cd4c5f06e0',
    messagingSenderId: '812229010081',
    projectId: 'arcon-2023',
    storageBucket: 'arcon-2023.appspot.com',
    iosClientId: '812229010081-it1rgao99427lp2d25gbm8skjj3akmvk.apps.googleusercontent.com',
    iosBundleId: 'com.example.arconApp.RunnerTests',
  );
}
